apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lb
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # Exposed externally
      targetPort: 80  # Maps to container port
  type: LoadBalancer
